version: 2
jobs:
  build:
    docker:
      - image: nvidia/cuda:9.2-devel-ubuntu18.04
    steps:
      - run: apt-get update && apt-get install -qy git cmake mesa-common-dev libidn11-dev python3-requests python3-git

      - checkout
      - run: git submodule update --init --recursive

      - run: cmake -DHUNTER_JOBS_NUMBER=4 -DETHASHCUDA=ON -DAPICORE=ON -H. -Bbuild
      - run: cmake --build build -- -j4
      - store_artifacts:
          path: build/ethcoreminer/ethcoreminer
          destination: ethcoreminer
